const images=[
{
     indianimages:[
    {
        id:1,
        src:'Images/Indianfood/Indian1.jpg',
        name:'Puri',
        category:'Indianfood',
    },
    {
        id:2,
        src:'Images/Indianfood/Indian2.jpg',
        name:'GrilledChicken',
        category:'Indianfood',
    },
    {
        id:3,
        src:'Images/Indianfood/Indian3.jpg',
        name:'Idiyappam',
        category:'Indianfood',
    },
    {
        id:4,
        src:'Images/Indianfood/Indian4.jpg',
        name:'Rice',
        category:'Indianfood',
    },
    {
        id:5,
        src:'Images/Indianfood/Indian5.jpg',
        name:'Idly',
        category:'Indianfood',
    },
    {
        id:6,
        src:'Images/Indianfood/Indian6.jpg',
        name:'PineappleCurry',
        category:'Indianfood',
    },
    {
        id:7,
        src:'Images/Indianfood/Indian7.png',
        name:'PavBhaji',
        category:'Indianfood',
    },
    {
        id:8,
        src:'Images/Indianfood/Indian8.png',
        name:'Fish',
        category:'Indianfood',
    },
    {
        id:9,
        src:'Images/Indianfood/Indian9.png',
        name:'Biryani',
        category:'Indianfood',
    },
    {
        id:10,
        src:'Images/Indianfood/Indian1.jpg',
        name:'Vada',
        category:'Indianfood',
    },
]
},
{
chineseimages:[
    {
        id:11,
        src:'Images/Chinesefood/AppetizerEggroll.jpg',
        name:'AppetizerEggroll',
        category:'Chinesefood',
    },
    {
        id:12,
        src:'Images/Chinesefood/BambooBasket.jpg',
        name:'BambooBasket',
        category:'Chinesefood',
    },
    {
        id:13,
        src:'Images/Chinesefood/BeefBrocoli.jpg',
        name:'BeefBrocoli',
        category:'Chinesefood',
    },
    {
        id:14,
        src:'Images/Chinesefood/CharSiuPork.jpg',
        name:'CharSiuPork',
        category:'Chinesefood',
    },
    {
        id:15,
        src:'Images/Chinesefood/ChowMeinNoodles.jpg',
        name:'ChowMeinNoodles',
        category:'Chinesefood',
    },
    {
        id:16,
        src:'Images/Chinesefood/FriedChowMein.jpg',
        name:'FriedChowMein',
        category:'Chinesefood',
    },
    {
        id:17,
        src:'Images/Chinesefood/FriedMushrooms.jpg',
        name:'FriedMushrooms',
        category:'Chinesefood',
    },
    {
        id:18,
        src:'Images/Chinesefood/GreenBeans.jpg',
        name:'GreenBeans',
        category:'Chinesefood',
    },
    {
        id:19,
        src:'Images/Chinesefood/SpicySesameChicken.jpg',
        name:'SpicySesameChicken',
        category:'Chinesefood',
    },
    {
        id:20,
        src:'Images/Chinesefood/WalnatShrimp.jpg',
        name:'WalnatShrimp',
        category:'Chinesefood',
    },
]}
];
export default images;